name: seshasai_subrahmanyam_portfolio
description: A Flutter Web portfolio for a Senior Flutter Developer & Generative AI Engineer with RAG/CAG chat capabilities.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Routing
  go_router: ^12.1.1
  
  # Networking
  dio: ^5.4.0
  
  # Markdown Rendering
  flutter_markdown: ^0.6.18
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # URL Launcher
  url_launcher: ^6.2.2
  
  
  # Animations
  flutter_animate: ^4.3.0
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/resume.json
    # - assets/availability.json
    - assets/resume.pdf
    - assets/images/
    - assets/images/project_thumbs/
    - assets/fonts/
    - assets/icons/
    - assets/icons/langchain.svg
    - assets/icons/mcp.svg
    - assets/icons/flutter.svg
    - assets/icons/n8n.svg
    - assets/icons/make.svg
    - assets/icons/google_adk.svg
    - assets/icons/a2a.svg
    - assets/icons/context_eng.svg
    - assets/icons/linkedin.svg
    - assets/images/my_face.jpeg
    - assets/icons/github.svg
    - assets/icons/junnu_ai.svg
    - assets/icons/medium.svg
 
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
